[module]
steps = [
    { kind = "install-package", package = "greetd-tuigreet" },
    { kind = "write-file", path = "/etc/greetd/config.toml", content = """
[terminal]
vt = 1

[default_session]
command = "tuigreet --time --asterisks --remember --cmd Hyprland"
user = "greeter"
""", overwrite = true },
    "systemctl enable greetd",
]
