# stable
hard_tabs = true
edition = "2021"
max_width = 120
reorder_imports = true
newline_style = "Unix"

# unstable
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
condense_wildcard_suffixes = true
format_strings = true
hex_literal_case = "Upper"
overflow_delimited_expr = true
reorder_impl_items = true
