[module]
commands = [
    { kind = "install-packages", packages = [
        "git",
        "mold",
        "clang",
        "rustup",
    ] },
    { kind = "write-file", path = "~/.cargo/config.toml", content = """
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
""" },
    "rustup default stable",
    "rustup toolchain install nightly",
]
