[config]
# aur-helper = "paru"
aur-helper = "paru"

[module]
includes = ["modules/greetd.toml", "modules/dev.toml", "modules/pipewire.toml"]
commands = [
    { kind = "install-packages", packages = [
        "hyprland",
        "foot",
        "fish",
        "eza",
        "bat",
        "btop",
    ] },
    { kind = "install-package", package = "mercury-browser-avx2-bin", aur = true },
]
