[config]
aur-helper = "yay"
host-includes = [{ hostname = "nya", includes = ["./hosts/nya.toml"] }]

[module]
includes = "./modules/term.toml"

steps = [
   { kind = "install-package", package = "firefox" },
   { kind = "install-package", package = "zed-preview-bin", aur = true },

   { kind = "install-packages", packages = [
      "vesktop",
   ], aur = true },

   [
      "sudo pacman -Sy --needed --noconfirm fastfetch",
      "sudo pacman -Sy --needed --noconfirm base-devel git clang",
   ],
]
